"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp, CheckCircle2, Copy, Check } from "lucide-react";
import type { MockProfile, MockDimensionScore } from "@/lib/mock-profiles";

const DIM_COLORS: Record<string, string> = {
  automation: "#3b82f6",
  memory: "#10b981",
  agentCoverage: "#8b5cf6",
  toolIntegrations: "#f59e0b",
  skillBreadth: "#f43f5e",
  workflowDepth: "#06b6d4",
};

function generateSummary(profile: MockProfile): string {
  const total = profile.dimensions.reduce((sum, d) => sum + d.score, 0);
  const strong = profile.dimensions
    .filter((d) => d.score >= 7)
    .map((d) => d.label);
  const weak = profile.dimensions
    .filter((d) => d.score <= 4)
    .map((d) => d.label);

  let summary = `@${profile.username} has an AgentScore of ${profile.composite} (${profile.tier}), computed as ${total} / 6 = ${profile.composite}.`;

  if (strong.length > 0) {
    summary += ` Top-performing dimensions: ${strong.join(", ")}.`;
  }
  if (weak.length > 0) {
    summary += ` Areas with the most room to grow: ${weak.join(", ")}.`;
  }

  const metCount = profile.dimensions.reduce(
    (sum, d) => sum + d.signals.filter((s) => s.met).length,
    0
  );
  const totalSignals = profile.dimensions.reduce(
    (sum, d) => sum + d.signals.length,
    0
  );
  summary += ` ${metCount} of ${totalSignals} signals met across all dimensions.`;

  return summary;
}

function generateMarkdownReport(profile: MockProfile): string {
  const lines: string[] = [];
  const total = profile.dimensions.reduce((sum, d) => sum + d.score, 0);

  lines.push(`# AgentScore Report: @${profile.username}`);
  lines.push("");
  lines.push(`**Score:** ${profile.composite} / 10 (${profile.tier} — ${profile.tierDescription})`);
  lines.push(`**Composite:** (${profile.dimensions.map((d) => d.score).join(" + ")}) / 6 = ${profile.composite}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(generateSummary(profile));
  lines.push("");

  for (const dim of profile.dimensions) {
    const maxScore = dim.maxScore ?? 10;
    lines.push(`## ${dim.label} — ${dim.score}/${maxScore}`);
    lines.push("");
    lines.push("| Signal | Status | Points |");
    lines.push("|--------|--------|--------|");
    for (const sig of dim.signals) {
      const earned = sig.earned ?? (sig.met ? 1 : 0);
      const max = sig.max ?? 1;
      const status = sig.met ? "Pass" : "—";
      lines.push(`| ${sig.signal} | ${status} | ${earned}/${max} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by AgentScore*");

  return lines.join("\n");
}

function SignalTable({ dim }: { dim: MockDimensionScore }) {
  const color = DIM_COLORS[dim.dimension] ?? "#6b7280";
  const maxScore = dim.maxScore ?? 10;

  return (
    <div className="rounded-xl bg-[#12121a] border border-white/10 overflow-hidden">
      <div
        className="flex items-center justify-between px-5 py-3"
        style={{ borderBottom: `1px solid ${color}30` }}
      >
        <h3 className="font-semibold text-white text-sm">{dim.label}</h3>
        <span className="font-mono text-sm font-bold" style={{ color }}>
          {dim.score}/{maxScore}
        </span>
      </div>
      <table className="w-full text-xs">
        <thead>
          <tr className="text-white/40 uppercase tracking-wider">
            <th className="text-left px-5 py-2 font-medium">Signal</th>
            <th className="text-center px-3 py-2 font-medium w-16">Status</th>
            <th className="text-right px-5 py-2 font-medium w-20">Points</th>
          </tr>
        </thead>
        <tbody>
          {dim.signals.map((sig) => {
            const earned = sig.earned ?? (sig.met ? 1 : 0);
            const max = sig.max ?? 1;
            return (
              <tr
                key={sig.signal}
                className="border-t border-white/5"
              >
                <td className={`px-5 py-2.5 ${sig.met ? "text-white/70" : "text-white/30"}`}>
                  {sig.signal}
                </td>
                <td className="text-center px-3 py-2.5">
                  {sig.met ? (
                    <CheckCircle2 size={14} className="inline text-emerald-500" />
                  ) : (
                    <span className="inline-block h-3.5 w-3.5 rounded-full border border-white/20" />
                  )}
                </td>
                <td className={`text-right px-5 py-2.5 font-mono ${sig.met ? "text-emerald-400" : "text-white/20"}`}>
                  {earned}/{max}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

export default function FullReport({ profile }: { profile: MockProfile }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const total = profile.dimensions.reduce((sum, d) => sum + d.score, 0);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdownReport(profile));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // clipboard write failed
    }
  };

  return (
    <div className="rounded-xl bg-[#0a0a12] border border-white/10 overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-6 py-4 hover:bg-white/5 transition-colors"
      >
        <h2 className="text-lg font-semibold text-white">Full Report</h2>
        {open ? (
          <ChevronUp size={20} className="text-white/50" />
        ) : (
          <ChevronDown size={20} className="text-white/50" />
        )}
      </button>

      {open && (
        <div className="px-6 pb-6 space-y-8">
          {/* Summary */}
          <div>
            <h3 className="text-xs uppercase tracking-widest text-white/40 mb-3">
              Summary
            </h3>
            <p className="text-sm text-white/70 leading-relaxed">
              {generateSummary(profile)}
            </p>
          </div>

          {/* Composite calculation */}
          <div className="rounded-xl bg-[#12121a] border border-white/10 p-5">
            <h3 className="text-xs uppercase tracking-widest text-white/40 mb-3">
              Composite Calculation
            </h3>
            <div className="flex items-center gap-2 text-sm font-mono">
              <span className="text-white/50">(</span>
              {profile.dimensions.map((d, i) => (
                <span key={d.dimension}>
                  <span style={{ color: DIM_COLORS[d.dimension] ?? "#6b7280" }}>
                    {d.score}
                  </span>
                  {i < profile.dimensions.length - 1 && (
                    <span className="text-white/30"> + </span>
                  )}
                </span>
              ))}
              <span className="text-white/50">)</span>
              <span className="text-white/30"> / </span>
              <span className="text-white/50">6</span>
              <span className="text-white/30"> = </span>
              <span className="text-white font-bold">{profile.composite}</span>
            </div>
            <div className="mt-2 flex gap-3 text-xs text-white/30">
              {profile.dimensions.map((d) => (
                <span key={d.dimension} style={{ color: `${DIM_COLORS[d.dimension]}80` }}>
                  {d.label}
                </span>
              ))}
            </div>
          </div>

          {/* Per-dimension signal tables */}
          <div>
            <h3 className="text-xs uppercase tracking-widest text-white/40 mb-4">
              Signal-by-Signal Breakdown
            </h3>
            <div className="space-y-4">
              {profile.dimensions.map((dim) => (
                <SignalTable key={dim.dimension} dim={dim} />
              ))}
            </div>
          </div>

          {/* Export button */}
          <div className="flex justify-end">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 rounded-lg px-4 py-2 text-sm bg-white/5 border border-white/10 text-white/60 hover:text-white hover:bg-white/10 transition-colors"
            >
              {copied ? (
                <>
                  <Check size={14} className="text-emerald-400" />
                  <span className="text-emerald-400">Copied as Markdown</span>
                </>
              ) : (
                <>
                  <Copy size={14} />
                  <span>Export as Markdown</span>
                </>
              )}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
